[package]
name = "whkd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8"
color-eyre = "0.6"
dirs = "4"
lazy_static = "1"
parking_lot = "0.12"
windows-hotkeys = "0.1.1"